# Copyright 2026 bitHeads, Inc. All Rights Reserved.
class_name OperationParam
extends RefCounted

# Service message envelope
const SERVICE_MESSAGE_PACKET_ID := "packetId"
const SERVICE_MESSAGE_PROFILE_ID := "profileId"
const SERVICE_MESSAGE_SESSION_ID := "sessionId"
const SERVICE_MESSAGE_GAME_ID := "gameId"
const SERVICE_MESSAGE_MESSAGES := "messages"
const SERVICE_MESSAGE_SERVICE := "service"
const SERVICE_MESSAGE_OPERATION := "operation"
const SERVICE_MESSAGE_DATA := "data"

# Authenticate
const AUTHENTICATE_SERVICE_AUTHENTICATE_AUTHENTICATION_TYPE := "authenticationType"
const AUTHENTICATE_SERVICE_AUTHENTICATE_AUTHENTICATION_TOKEN := "authenticationToken"
const AUTHENTICATE_SERVICE_AUTHENTICATE_EXTERNAL_ID := "externalId"
const AUTHENTICATE_SERVICE_AUTHENTICATE_UNIVERSAL_ID := "universalId"
const AUTHENTICATE_SERVICE_AUTHENTICATE_GAME_ID := "gameId"
const AUTHENTICATE_SERVICE_AUTHENTICATE_DEVICE_ID := "deviceId"
const AUTHENTICATE_SERVICE_AUTHENTICATE_FORCE_MERGE_FLAG := "forceMergeFlag"
const AUTHENTICATE_SERVICE_AUTHENTICATE_RELEASE_PLATFORM := "releasePlatform"
const AUTHENTICATE_SERVICE_AUTHENTICATE_GAME_VERSION := "gameVersion"
const AUTHENTICATE_SERVICE_AUTHENTICATE_BRAINCLOUD_VERSION := "clientLibVersion"
const AUTHENTICATE_SERVICE_AUTHENTICATE_EXTERNAL_AUTH_NAME := "externalAuthName"
const AUTHENTICATE_SERVICE_AUTHENTICATE_EMAIL_ADDRESS := "emailAddress"
const AUTHENTICATE_SERVICE_AUTHENTICATE_SERVICE_PARAMS := "serviceParams"
const AUTHENTICATE_SERVICE_AUTHENTICATE_TOKEN_TTL_IN_MINUTES := "tokenTtlInMinutes"
const AUTHENTICATE_SERVICE_AUTHENTICATE_LEVEL_NAME := "levelName"
const AUTHENTICATE_SERVICE_AUTHENTICATE_PEER_CODE := "peerCode"
const AUTHENTICATE_SERVICE_AUTHENTICATE_COUNTRY_CODE := "countryCode"
const AUTHENTICATE_SERVICE_AUTHENTICATE_LANGUAGE_CODE := "languageCode"
const AUTHENTICATE_SERVICE_AUTHENTICATE_TIME_ZONE_OFFSET := "timeZoneOffset"
const AUTHENTICATE_SERVICE_AUTHENTICATE_AUTH_UPGRADE_ID := "upgradeAppId"
const AUTHENTICATE_SERVICE_AUTHENTICATE_ANONYMOUS_ID := "anonymousId"
const AUTHENTICATE_SERVICE_AUTHENTICATE_PROFILE_ID := "profileId"
const AUTHENTICATE_SERVICE_AUTHENTICATE_FORCE_CREATE := "forceCreate"
const AUTHENTICATE_SERVICE_AUTHENTICATE_COMPRESS_RESPONSE := "compressResponse"
const AUTHENTICATE_SERVICE_PLAYER_SESSION_EXPIRY := "playerSessionExpiry"

const PROFILE_ID := "profileId"

# Entity service
const ENTITY_SERVICE_ENTITY_TYPE := "entityType"
const ENTITY_SERVICE_ENTITY_ID := "entityId"
const ENTITY_SERVICE_ENTITY_DATA := "data"
const ENTITY_SERVICE_ACL := "acl"
const ENTITY_SERVICE_ENTITY_VERSION := "version"
const ENTITY_SERVICE_FRIEND_ID := "friendId"
const ENTITY_SERVICE_TARGET_PLAYBACK_VERSION := "targetVersion"

# Global Entity
const GLOBAL_ENTITY_SERVICE_ENTITY_TYPE := "entityType"
const GLOBAL_ENTITY_SERVICE_ENTITY_ID := "entityId"
const GLOBAL_ENTITY_SERVICE_ENTITY_INDEX_ID := "entityIndexedId"
const GLOBAL_ENTITY_SERVICE_WHERE := "where"
const GLOBAL_ENTITY_SERVICE_ORDER_BY := "orderBy"
const GLOBAL_ENTITY_SERVICE_MAX_RETURN := "maxReturn"
const GLOBAL_ENTITY_SERVICE_DATA := "data"
const GLOBAL_ENTITY_SERVICE_ACL := "acl"
const GLOBAL_ENTITY_SERVICE_VERSION := "version"
const GLOBAL_ENTITY_SERVICE_TIME_TO_LIVE := "timeToLive"
const GLOBAL_ENTITY_SERVICE_INDEXED_ID := "entityIndexedId"
const GLOBAL_ENTITY_SERVICE_CONTEXT := "context"
const GLOBAL_ENTITY_SERVICE_PAGE_OFFSET := "pageOffset"

# Player State
const PLAYER_STATE_SERVICE_UPDATE_NAME := "playerName"
const PLAYER_STATE_SERVICE_ATTRIBUTES := "attributes"
const PLAYER_STATE_SERVICE_WIPE_EXISTING := "wipeExisting"
const PLAYER_STATE_SERVICE_STATUS_NAME := "statusName"
const PLAYER_STATE_SERVICE_ADDITIONAL_SECS := "additionalSecs"
const PLAYER_STATE_SERVICE_DURATION := "duration"
const PLAYER_STATE_SERVICE_DURATION_SECS := "durationSecs"
const PLAYER_STATE_SERVICE_DATA := "data"
const PLAYER_STATE_SERVICE_DETAILS := "details"
const PLAYER_STATE_SERVICE_SUMMARY := "playerSummaryData"
const PLAYER_STATE_SERVICE_PICTURE_URL := "playerPictureUrl"
const PLAYER_STATE_SERVICE_CONTACT_EMAIL := "contactEmail"
const PLAYER_STATE_SERVICE_NEW_NAME := "newName"
const PLAYER_STATE_SERVICE_TIMEZONE_OFFSET := "timeZoneOffset"
const PLAYER_STATE_SERVICE_LANGUAGE_CODE := "languageCode"

# Player Statistics
const PLAYER_STATISTICS_SERVICE_STATISTICS := "statistics"
const PLAYER_STATISTICS_SERVICE_EXPERIENCE_POINTS := "xp_points"

# Global Statistics
const GLOBAL_STATISTICS_SERVICE_STATISTICS := "statistics"

# Script
const SCRIPT_SERVICE_RUN_SCRIPT_NAME := "scriptName"
const SCRIPT_SERVICE_RUN_SCRIPT_DATA := "scriptData"
const SCRIPT_SERVICE_SCHEDULED_START_TIME := "startDateUTC"
const SCRIPT_SERVICE_RUN_SCRIPT_JOB_ID := "jobId"
const SCRIPT_SERVICE_PEER_CODE := "peer"
const SCRIPT_SERVICE_PARENT_LEVEL := "parentLevel"

# Identity
const IDENTITY_SERVICE_EXTERNAL_ID := "externalId"
const IDENTITY_SERVICE_AUTHENTICATION_TYPE := "authenticationType"
const IDENTITY_SERVICE_CONFIRM_PROFILE_ID := "confirmChangeOfProfile"
const IDENTITY_SERVICE_OLD_ANONYMOUS_ID := "oldAnonymousId"
const IDENTITY_SERVICE_NEW_ANONYMOUS_ID := "newAnonymousId"
const IDENTITY_SERVICE_AUTHENTICATION_TOKEN := "authenticationToken"
const IDENTITY_SERVICE_FORCE_CREATE := "forceCreate"
const IDENTITY_SERVICE_EXTERNAL_AUTH_NAME := "externalAuthName"

# Event
const EVENT_SERVICE_SEND_TO_PLAYER_ID := "toId"
const EVENT_SERVICE_SEND_EVENT_TYPE := "eventType"
const EVENT_SERVICE_SEND_EVENT_DATA := "eventData"
const EVENT_SERVICE_UPDATE_EVENT_DATA := "eventData"
const EVENT_SERVICE_EVENT_ID := "evId"
const EVENT_SERVICE_INCLUDE_SENT_EVENTS := "includePublishedByMe"
const EVENT_SERVICE_DELETE_INCOMING_EVENTS_IDS := "evIds"
const EVENT_SERVICE_DELETE_INCOMING_EVENTS_OLDER_THAN := "dateMillis"
const EVENT_SERVICE_DELETE_INCOMING_EVENTS_FILTER := "filter"

# Friend
const FRIEND_SERVICE_AUTH_TYPE := "authenticationType"
const FRIEND_SERVICE_EXTERNAL_ID := "externalId"
const FRIEND_SERVICE_PROFILE_ID := "profileId"
const FRIEND_SERVICE_FRIEND_PLATFORM := "friendPlatform"
const FRIEND_SERVICE_EXTERNAL_ID_ARRAY := "externalIds"
const FRIEND_SERVICE_PROFILE_IDS := "profileIds"
const FRIEND_SERVICE_ENTITY_ID := "entityId"
const FRIEND_SERVICE_ENTITY_TYPE := "entityType"
const FRIEND_SERVICE_INCLUDE_SUMMARY_DATA := "includeSummaryData"
const FRIEND_SERVICE_MAX_RESULTS := "maxResults"
const FRIEND_SERVICE_FRIEND_ID := "friendId"
const FRIEND_SERVICE_USER_NAME := "searchText"

# Leaderboard
const SOCIAL_LEADERBOARD_SERVICE_LEADERBOARD_ID := "leaderboardId"
const SOCIAL_LEADERBOARD_SERVICE_LEADERBOARD_IDS := "leaderboardIds"
const SOCIAL_LEADERBOARD_SERVICE_SORT := "sort"
const SOCIAL_LEADERBOARD_SERVICE_INCLUDE_PLAYER_SCORE := "includeLeaderboardEntryData"
const SOCIAL_LEADERBOARD_SERVICE_BEFORE_COUNT := "beforeCount"
const SOCIAL_LEADERBOARD_SERVICE_AFTER_COUNT := "afterCount"
const SOCIAL_LEADERBOARD_SERVICE_SCORE := "score"
const SOCIAL_LEADERBOARD_SERVICE_BEST_SCORE := "bestScore"
const SOCIAL_LEADERBOARD_SERVICE_DATA := "data"
const SOCIAL_LEADERBOARD_SERVICE_REPLACE_SCORE := "replaceName"
const SOCIAL_LEADERBOARD_SERVICE_PROFILE_IDS := "profileIds"
const SOCIAL_LEADERBOARD_SERVICE_NUM_RESULTS_TO_RETURN := "numResults"
const SOCIAL_LEADERBOARD_SERVICE_LEADERBOARD_RESULT_COUNT := "leaderboardResultCount"
const SOCIAL_LEADERBOARD_SERVICE_START_INDEX := "startIndex"
const SOCIAL_LEADERBOARD_SERVICE_END_INDEX := "endIndex"
const SOCIAL_LEADERBOARD_SERVICE_VERSION_ID := "versionId"
const SOCIAL_LEADERBOARD_SERVICE_START_DATE := "startDate"
const SOCIAL_LEADERBOARD_SERVICE_END_DATE := "endDate"
const SOCIAL_LEADERBOARD_SERVICE_LEADERBOARD_TYPE := "leaderboardType"
const SOCIAL_LEADERBOARD_SERVICE_ROTATION_TYPE := "rotationType"
const SOCIAL_LEADERBOARD_SERVICE_ROTATION_RESET := "rotationResetTime"
const SOCIAL_LEADERBOARD_SERVICE_RETAIN_COUNT := "retainedCount"
const SOCIAL_LEADERBOARD_SERVICE_SCORE_DATA := "scoreData"
const SOCIAL_LEADERBOARD_SERVICE_CONFIG_JSON := "configJson"

# Gamification
const GAMIFICATION_SERVICE_INCLUDE_META_DATA := "includeMetaData"
const GAMIFICATION_SERVICE_ACHIEVEMENTS_NAME := "achievementIds"
const GAMIFICATION_SERVICE_MILESTONES_CATEGORY := "category"
const GAMIFICATION_SERVICE_QUESTS_CATEGORY := "category"

# Matchmaking
const MATCH_MAKING_SERVICE_PLAYER_RATING := "playerRating"
const MATCH_MAKING_SERVICE_MIN_RATING := "minRating"
const MATCH_MAKING_SERVICE_MAX_RATING := "maxRating"
const MATCH_MAKING_SERVICE_ATTRIBUTES := "attributes"
const MATCH_MAKING_SERVICE_EXTRA_PARMS := "extraParms"
const MATCH_MAKING_SERVICE_DAYS_OF_WEEK := "daysOfWeek"
const MATCH_MAKING_SERVICE_PUSH_CONTENT := "pushContent"
const MATCH_MAKING_SERVICE_PLAYER_FILTER := "playerFilter"
const MATCH_MAKING_SERVICE_NUM_MATCHES := "numMatches"

# One-Way Match
const ONE_WAY_MATCH_SERVICE_PLAYER_ID := "playerId"
const ONE_WAY_MATCH_SERVICE_RANGE_DELTA := "rangeDelta"
const ONE_WAY_MATCH_SERVICE_PLAY_BACK_STREAM_ID := "playbackStreamId"

# Playback Stream
const PLAYBACK_STREAM_SERVICE_PLAYBACK_STREAM_ID := "playbackStreamId"
const PLAYBACK_STREAM_SERVICE_TARGET_PLAYER_ID := "targetPlayerId"
const PLAYBACK_STREAM_SERVICE_INCLUDE_SHARED_DATA := "includeSharedData"
const PLAYBACK_STREAM_SERVICE_EVENT_DATA := "eventData"
const PLAYBACK_STREAM_SERVICE_SUMMARY := "summaryData"
const PLAYBACK_STREAM_SERVICE_MAX_NUM_RETURNED := "maxNumStreams"

# Async Match
const ASYNC_MATCH_SERVICE_OPPONENTS := "players"
const ASYNC_MATCH_SERVICE_PUSH_MESSAGE := "pushContent"
const ASYNC_MATCH_SERVICE_OWNER_ID := "ownerId"
const ASYNC_MATCH_SERVICE_MATCH_ID := "matchId"
const ASYNC_MATCH_SERVICE_TURN_DATA := "matchState"
const ASYNC_MATCH_SERVICE_SUMMARY := "summary"
const ASYNC_MATCH_SERVICE_STATUS := "status"
const ASYNC_MATCH_SERVICE_CURRENT_VERSION := "version"

# Push Notification
const PUSH_NOTIFICATION_REGISTER_PARAM_DEVICE_TYPE := "deviceType"
const PUSH_NOTIFICATION_REGISTER_PARAM_DEVICE_TOKEN := "deviceToken"
const PUSH_NOTIFICATION_SEND_PARAM_TO_PLAYER_ID := "toPlayerId"
const PUSH_NOTIFICATION_SEND_PARAM_PROFILE_ID := "profileId"
const PUSH_NOTIFICATION_SEND_PARAM_MESSAGE := "message"
const PUSH_NOTIFICATION_SEND_PARAM_NOTIFICATION_TEMPLATE_ID := "notificationTemplateId"
const PUSH_NOTIFICATION_SEND_PARAM_SUBSTITUTIONS := "substitutions"
const PUSH_NOTIFICATION_SEND_PARAM_PROFILE_IDS := "profileIds"
const PUSH_NOTIFICATION_SEND_PARAM_FCM_CONTENT := "fcmContent"
const PUSH_NOTIFICATION_SEND_PARAM_IOS_CONTENT := "iosContent"
const PUSH_NOTIFICATION_SEND_PARAM_FACEBOOK_CONTENT := "facebookContent"
const ALERT_CONTENT := "alertContent"
const CUSTOM_DATA := "customData"
const START_DATE_UTC := "startDateUTC"
const MINUTES_FROM_NOW := "minutesFromNow"

# File
const PREPARE_USER_UPLOAD_CLOUD_PATH := "cloudPath"
const PREPARE_USER_UPLOAD_CLOUD_FILENAME := "cloudFilename"
const PREPARE_USER_UPLOAD_SHAREABLE := "shareable"
const PREPARE_USER_UPLOAD_REPLACE_IF_EXISTS := "replaceIfExists"
const PREPARE_USER_UPLOAD_FILE_SIZE := "fileSize"
const PREPARE_USER_UPLOAD_RECURSIVE_DELETE := "recurse"

# Global File V3
const GLOBAL_FILE_FILENAME := "filename"
const GLOBAL_FILE_FOLDER_PATH := "folderPath"
const GLOBAL_FILE_TREE_ID := "treeId"
const GLOBAL_FILE_FILE_ID := "fileId"
const GLOBAL_FILE_RECURSIVE := "recurse"
const GLOBAL_FILE_ACL := "acl"
const GLOBAL_FILE_VERSION := "version"
const GLOBAL_FILE_OVERWRITE_IF_PRESENT := "overwriteIfPresent"
const GLOBAL_FILE_FILE_SIZE := "fileSize"

# Group
const GROUP_ID := "groupId"
const GROUP_TYPE := "groupType"
const GROUP_NAME := "name"
const GROUP_IS_OPEN_GROUP := "isOpenGroup"
const GROUP_ACL := "acl"
const GROUP_DATA := "data"
const GROUP_OWNER_ATTRIBUTES := "ownerAttributes"
const GROUP_DEFAULT_MEMBER_ATTRIBUTES := "defaultMemberAttributes"
const GROUP_PROFILE_ID := "profileId"
const GROUP_ROLE := "role"
const GROUP_ATTRIBUTES := "attributes"
const GROUP_CONTEXT := "context"
const GROUP_PAGE_OFFSET := "pageOffset"
const GROUP_ENTITY_TYPE := "entityType"
const GROUP_ENTITY_ID := "entityId"
const GROUP_VERSION := "version"
const GROUP_ENTITY_VERSION := "version"
const GROUP_ENTITY_DATA := "data"
const GROUP_ENTITY_ACL := "acl"
const GROUP_SUMMARY_DATA := "summaryData"
const GROUP_AUTO_JOIN_STRATEGY := "autoJoinStrategy"
const GROUP_WHERE := "where"

# Chat
const CHAT_CHANNEL_ID := "channelId"
const CHAT_CONTENT := "content"
const CHAT_PLAIN_TEXT := "text"
const CHAT_MAX_RETURN := "maxReturn"
const CHAT_MSG_ID := "msgId"
const CHAT_VERSION := "version"
const CHAT_RICH := "rich"

# Messaging
const MESSAGING_MESSAGE_BOX := "msgbox"
const MESSAGING_PROFILE_IDS := "toProfileIds"
const MESSAGING_CONTENT_TEXT := "text"
const MESSAGING_CONTENT := "contentJson"
const MESSAGING_MAX_RETURN := "maxReturn"
const MESSAGING_PAGE_OFFSET := "pageOffset"
const MESSAGING_MSG_IDS := "msgIds"
const MESSAGING_MARK_AS_READ := "markAsRead"

# Lobby
const LOBBY_TYPE := "lobbyType"
const LOBBY_RATING := "rating"
const LOBBY_ALGO := "algo"
const LOBBY_FILTER_JSON := "filterJson"
const LOBBY_SETTINGS := "settings"
const LOBBY_IS_READY := "isReady"
const LOBBY_EXTRA_JSON := "extraJson"
const LOBBY_TEAM := "team"
const LOBBY_TO_TEAM_CODE := "toTeamCode"
const LOBBY_SIGNAL_DATA := "signalData"
const LOBBY_ID := "lobbyId"
const LOBBY_PING_DATA := "pingData"
const LOBBY_OTHER_USER_CX_IDS := "otherUserCxIds"
const LOBBY_IS_NEW_LOBBY := "isNewLobby"
const LOBBY_MAX_STEPS := "maxSteps"
const LOBBY_CONNECTION_ID := "cxId"
const LOBBY_TYPES := "lobbyTypes"
const LOBBY_CRITERIA := "criteriaJson"
const LOBBY_ENTRY_ID := "entryId"
const LOBBY_CONFIG_OVERRIDES := "configOverrides"

# Presence
const PRESENCE_PLATFORM := "platform"
const PRESENCE_INCLUDE_OFFLINE := "includeOffline"
const PRESENCE_GROUP_ID := "groupId"
const PRESENCE_PROFILE_IDS := "profileIds"
const PRESENCE_BIDIRECTIONAL := "bidirectional"
const PRESENCE_ACTIVITY := "activity"
const PRESENCE_VISIBLE := "visible"

# Profanity
const PROFANITY_TEXT := "text"
const PROFANITY_REPLACE_SYMBOL := "replaceSymbol"
const PROFANITY_FLAG_EMAIL := "flagEmail"
const PROFANITY_FLAG_PHONE := "flagPhone"
const PROFANITY_FLAG_URLS := "flagUrls"
const PROFANITY_LANGUAGE := "languages"

# Redemption Code
const REDEMPTION_CODE_ID := "scanCode"
const REDEMPTION_CODE_TYPE := "codeType"
const REDEMPTION_CODE_CUSTOM_REDEMPTION_INFO := "customRedemptionInfo"

# Virtual Currency
const VIRTUAL_CURRENCY_ID := "vcId"
const VIRTUAL_CURRENCY_AMOUNT := "vcAmount"
const VIRTUAL_CURRENCY_PEER := "peerCode"
const VIRTUAL_CURRENCY_PARENT := "levelName"

# App Store
const APP_STORE_STORE_ID := "storeId"
const APP_STORE_RECEIPT_DATA := "receiptData"
const APP_STORE_PURCHASED_ITEM_ID := "itemId"
const APP_STORE_TRANS_INFO := "transactionData"
const APP_STORE_TRANSACTION_ID := "transactionId"

# Custom Entity
const CUSTOM_ENTITY_TYPE_NAME := "entityType"
const CUSTOM_ENTITY_DATA := "data"
const CUSTOM_ENTITY_ACL := "acl"
const CUSTOM_ENTITY_ENTITY_ID := "entityId"
const CUSTOM_ENTITY_VERSION := "version"
const CUSTOM_ENTITY_CONTEXT := "context"
const CUSTOM_ENTITY_PAGE_OFFSET := "pageOffset"
const CUSTOM_ENTITY_OWNER_ID := "ownerId"
const CUSTOM_ENTITY_COUNT := "count"
const CUSTOM_ENTITY_FIELDS_DATA := "fieldsJson"
const CUSTOM_ENTITY_INCREMENT_DATA := "fieldsJson"
const CUSTOM_ENTITY_NEW_OWNER_ID := "newOwnerId"
const CUSTOM_ENTITY_TIME_TO_LIVE := "timeToLive"
const CUSTOM_ENTITY_IS_OWNED := "isOwned"

# User Items
const USER_ITEMS_ITEM_DEF_ID := "defId"
const USER_ITEMS_VERSION := "version"
const USER_ITEMS_QUANTITY := "quantity"
const USER_ITEMS_USER_ITEM_ID := "itemId"
const USER_ITEMS_SHOP_ID := "shopId"
const USER_ITEMS_TO_PROFILE_ID := "profileId"
const USER_ITEMS_IMMEDIATE := "immediate"
const USER_ITEMS_INCLUDE_DEF := "includeDef"
const USER_ITEMS_CONTEXT := "context"
const USER_ITEMS_PAGE_OFFSET := "pageOffset"
const USER_ITEMS_SERVICE_OPTIONS_JSON := "optionsJson"

# Item Catalog
const ITEM_CATALOG_CONTEXT := "context"
const ITEM_CATALOG_PAGE_OFFSET := "pageOffset"
const ITEM_CATALOG_DEF_ID := "defId"

# Mail
const MAIL_FROM_NAME := "fromName"
const MAIL_FROM_ADDRESS := "fromAddress"
const MAIL_REPLY_TO_NAME := "replyToName"
const MAIL_REPLY_TO_ADDRESS := "replyToAddress"
const MAIL_TO_NAME := "toName"
const MAIL_TO_ADDRESS := "toAddress"
const MAIL_SUBJECT := "subject"
const MAIL_BODY := "body"
const MAIL_PROFILE_ID := "profileId"
const MAIL_SERVICE_PARAMS := "serviceParams"

# Blockchain
const BLOCK_CHAIN_CONFIG := "blockchainConfig"
const BLOCK_CHAIN_INTEGRATION_ID := "integrationId"
const BLOCK_CHAIN_CONTEXT := "contextJson"
const PUBLIC_KEY := "publicKey"

# Group File
const GROUP_FILE_ENTITY_TYPE := "entityType"
const GROUP_FILE_FOLDER_PATH := "folderPath"
const GROUP_FILE_FILENAME := "filename"
const GROUP_FILE_FULL_PATH_AND_FILE_NAME := "fullPathFilename"
const GROUP_FILE_CLOUD_PATH := "cloudPath"
const GROUP_FILE_CLOUD_FILENAME := "cloudFilename"
const GROUP_FILE_ACL := "acl"
const GROUP_FILE_VERSION := "version"
const GROUP_FILE_NEW_TREE_ID := "newTreeId"
const GROUP_FILE_NEW_FILENAME := "newFilename"
const GROUP_FILE_OVERWRITE_IF_PRESENT := "overwriteIfPresent"
const GROUP_FILE_GROUP_ID := "groupId"
const GROUP_FILE_FILE_ID := "fileId"
const GROUP_FILE_DELETE_IF_EXISTS := "deleteIfExists"
const GROUP_FILE_USER_CLOUD_PATH := "userCloudPath"
const GROUP_FILE_USER_CLOUD_FILENAME := "userCloudFilename"

# Tournament
const TOURNAMENT_LEADERBOARD_ID := "leaderboardId"
const TOURNAMENT_TOURNAMENT_CODE := "tournamentCode"
const TOURNAMENT_INITIAL_SCORE := "initialScore"
const TOURNAMENT_SCORE := "score"
const TOURNAMENT_DATA := "data"
const TOURNAMENT_ROUND_STARTED_EPOCH := "roundStartedEpoch"
const TOURNAMENT_VERSION_ID := "versionId"

# Data Stream
const DATA_STREAM_EVENT_NAME := "eventName"
const DATA_STREAM_EVENT_PROPERTIES := "eventProperties"
const DATA_STREAM_CRASH_INFO := "crashInfo"
const DATA_STREAM_EXTRAS := "extras"
